# Supabase CLI project configuration
[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
