"use client";

import { useI18n } from "@/lib/i18n";
import { useCitizenApplication } from "@/lib/dlas/citizen-view";
import { MATTERS, formatDateTime, label } from "@/lib/dlas/reference";
import ui from "@/components/dlao/dlao.module.css";

/** Citizen-visible testimony generated by the DLAO's lawyer-path close action. */
export function LawyerClosureTestimonialCard({ applicationId }: { applicationId: string }) {
  const { lang } = useI18n();
  const tx = (bn: string, en: string) => lang === "bn" ? bn : en;
  const testimony = useCitizenApplication(applicationId)?.lawyer?.closureTestimonial;
  if (!testimony) return null;

  const outcome = testimony.outcome.replaceAll("_", " ").toLowerCase();
  return (
    <section className={`${ui.flowStep} ${ui.confirmed}`} aria-label={tx("কেস বন্ধের প্রত্যয়নপত্র", "Case-closure testimonial")}>
      <span className={ui.confirmedBadge}>✓ {tx("কেস বন্ধের প্রত্যয়নপত্র", "CASE-CLOSURE TESTIMONIAL")}</span>
      <div className={`${ui.banner} ${ui.bannerWarn}`} style={{ marginTop: "var(--s-2)" }}>
        {tx("ডেমো / সিমুলেটেড — এটি প্রোটোটাইপ নথি; কোনো সরকারি সিল বা ই-স্বাক্ষর নেই।", "DEMO / SIMULATED — this is a prototype record with no official seal or e-signature.")}
      </div>
      <p>
        {tx(
          `${testimony.caseRef} নম্বর কেসে আইনজীবীর প্রতিনিধিত্ব সম্পন্ন, প্রযোজ্য সিমুলেটেড পেমেন্ট নথিভুক্ত এবং লিগ্যাল এইড অফিসার কেসটি বন্ধ করেছেন।`,
          `Legal representation for case ${testimony.caseRef} was completed, applicable simulated payments were recorded, and the Legal Aid Officer closed the case.`,
        )}
      </p>
      <div className={ui.rows}>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("প্রত্যয়নপত্র নং", "Testimonial no.")}</div><div className={ui.rowValue}><code>{testimony.testimonialId}</code></div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("কেস / আবেদন", "Case / application")}</div><div className={ui.rowValue}>{testimony.caseRef} · {testimony.applicationId}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("বিষয়", "Matter")}</div><div className={ui.rowValue}>{label(MATTERS, testimony.matter, lang)}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("পক্ষ", "Parties")}</div><div className={ui.rowValue}>{testimony.applicantName} · {testimony.respondentName ?? "—"}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("আইনজীবী", "Lawyer(s)")}</div><div className={ui.rowValue}>{testimony.lawyerNames.join(", ") || "—"}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("নথিভুক্ত শুনানি", "Recorded hearings")}</div><div className={ui.rowValue}>{testimony.hearingsRecorded}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("ফলাফল", "Outcome")}</div><div className={ui.rowValue}>{outcome} · {testimony.outcomeReason}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("বন্ধের কারণ", "Closure reason")}</div><div className={ui.rowValue}>{testimony.closureReason}</div></div>
        <div className={ui.row}><div className={ui.rowLabel}>{tx("ইস্যু করেছেন", "Issued by")}</div><div className={ui.rowValue}>{testimony.issuedByName} · {testimony.office} · {formatDateTime(testimony.issuedAt, lang)}</div></div>
      </div>
    </section>
  );
}
