"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/button";
import { useI18n } from "@/lib/i18n";
import { CourtAuthorityService, MediationFailureReviewService, formatDateTime, useMediationFailureRecord, useMediationFailureRecords, type FailureReferralPathway } from "@/lib/dlas";
import styles from "@/components/dlas/dlas.module.css";
import ui from "@/components/dlao/dlao.module.css";

type Lang = "bn" | "en";
const PATHWAYS: { code: FailureReferralPathway; bn: string; en: string }[] = [
  { code: "COURT_LEGAL_PATHWAY", bn: "আদালত / আইনি পথ", en: "Court / legal pathway" },
  { code: "LAWYER_ASSIGNMENT", bn: "আইনজীবী নিয়োগ", en: "Lawyer assignment" },
  { code: "FURTHER_LEGAL_AID_REVIEW", bn: "আরও লিগ্যাল এইড পর্যালোচনা", en: "Further legal aid review" },
  { code: "OTHER_REFERRAL", bn: "অন্য রেফারেল", en: "Other referral" },
];
const pathLabel = (path: FailureReferralPathway, lang: Lang) => PATHWAYS.find((x) => x.code === path)?.[lang] ?? path;
const statusLabel = (status: string, lang: Lang) => ({ AWAITING_OFFICER_REVIEW: { bn: "কর্মকর্তার পর্যালোচনা বাকি", en: "Awaiting officer review" }, MORE_INFORMATION_REQUESTED: { bn: "আরও তথ্য চাওয়া হয়েছে", en: "More information requested" }, REFERRAL_CONFIRMED: { bn: "রেফারেল নিশ্চিত", en: "Referral confirmed" } } as Record<string, { bn: string; en: string }>)[status]?.[lang] ?? status;
const suggestionReason = (path: FailureReferralPathway, lang: Lang) => ({ COURT_LEGAL_PATHWAY: { bn: "আদালত-প্রেরিত মধ্যস্থতার পর প্রযোজ্য আদালত বা আইনি প্রক্রিয়া পর্যালোচনা করুন।", en: "Review the applicable court or legal process after court-referred mediation." }, LAWYER_ASSIGNMENT: { bn: "নথিভুক্ত মামলার ধরনে মধ্যস্থতার পর প্রতিনিধিত্ব প্রয়োজন হতে পারে।", en: "The recorded case type may require representation after mediation." }, FURTHER_LEGAL_AID_REVIEW: { bn: "রেফারেলের আগে নথিভুক্ত মামলার তথ্য আরও পর্যালোচনা করুন।", en: "Review the recorded case information before referral." }, OTHER_REFERRAL: { bn: "মধ্যস্থতাকারীর প্রস্তাব অনুসরণ করা হয়েছে; কর্মকর্তার নিশ্চিতকরণ আবশ্যক।", en: "The suggestion follows the mediator proposal and requires officer confirmation." } } as Record<FailureReferralPathway, { bn: string; en: string }>)[path][lang];
function Row({ label, children }: { label: string; children: ReactNode }) { return <div className={ui.row}><div className={ui.rowLabel}>{label}</div><div className={ui.rowValue}>{children}</div></div>; }
function useTx() { const { lang } = useI18n(); return { lang: lang as Lang, tx: (bn: string, en: string) => lang === "bn" ? bn : en }; }

export function MediationFailureQueue() {
  const { lang, tx } = useTx();
  const cases = useMediationFailureRecords();
  return <div className={ui.readable}>
    <div className={ui.queuePlainHead}><span className={ui.heroKicker}>{tx("লিগ্যাল এইড অফিসার", "Legal Aid Officer")}</span><h1 className={ui.queueTitle}>{tx("মধ্যস্থতা ব্যর্থতা পর্যালোচনা", "Mediation failure reviews")}</h1><p className={styles.lead}>{tx("আনুষ্ঠানিক রেকর্ড দেখুন, সিস্টেমের পরামর্শ যাচাই করুন এবং পরবর্তী পথ মানবিকভাবে নিশ্চিত করুন।", "Review the formal record, assess the system suggestion, and make the human decision on the next pathway.")}</p></div>
    {!cases.length ? <div className={ui.banner}>{tx("এই অফিসে কোনো ব্যর্থ মধ্যস্থতার রেকর্ড নেই।", "No mediation failure records are available to this office.")}</div> : null}
    <div className={ui.worklist}>{cases.map((a) => { const record = a.mediation!.workspace!.failureRecord!; return <article className={ui.workItem} key={a.applicationId}><div className={ui.workItemHead}><div className={ui.workItemIdentity}><span className={ui.workItemEyebrow}>{a.caseId} · {record.recordId}</span><strong>{a.data.applicant.fullName} · {a.data.matter.opposingParty || tx("প্রতিপক্ষের নাম নেই", "Respondent not named")}</strong></div><span className={ui.tag}>{statusLabel(record.status, lang)}</span></div><p>{record.outcome}</p><div className={styles.hint}>{tx("সিস্টেমের পরামর্শ", "System suggestion")}: {pathLabel(record.systemSuggestion.pathway, lang)}</div><Link className={ui.textBtn} href={`/dashboard/dlo/mediation-outcomes/${encodeURIComponent(a.applicationId)}`}>{tx("অফিসার পর্যালোচনা খুলুন →", "Open officer review →")}</Link></article>; })}</div>
  </div>;
}

export function MediationFailureReview({ applicationId }: { applicationId: string }) {
  const { lang, tx } = useTx();
  const { officer, application: a, record } = useMediationFailureRecord(applicationId);
  const [selected, setSelected] = useState<FailureReferralPathway>(record?.systemSuggestion.pathway ?? "FURTHER_LEGAL_AID_REVIEW");
  const [note, setNote] = useState("");
  const [dispatchReference, setDispatchReference] = useState("");
  const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null);
  const run = (fn: () => unknown, success: string) => { try { fn(); setMessage({ ok: true, text: success }); } catch (error) { setMessage({ ok: false, text: error instanceof Error ? error.message : String(error) }); } };
  if (!officer) return <div className={ui.readable}><h1 className={styles.title}>{tx("লিগ্যাল এইড অফিসার পর্যালোচনা", "Legal Aid Officer review")}</h1><div className={ui.banner}>{tx("প্রথমে DLO পোর্টালে লগইন করুন।", "Sign in through the DLO portal first.")}</div></div>;
  if (!a || !record) return <div className={ui.readable}><Link className={ui.textBtn} href="/dashboard/dlo/mediation-outcomes">← {tx("কার্যতালিকা", "Worklist")}</Link><h1 className={styles.title}>{tx("রেকর্ড পাওয়া যায়নি", "Record not found")}</h1></div>;
  const attendance = (side: "APPLICANT" | "RESPONDENT") => record.attendance[side] === "PRESENT" ? tx("উপস্থিত", "Present") : record.attendance[side] === "REPRESENTED" ? tx("প্রতিনিধির মাধ্যমে", "Represented") : tx("অনুপস্থিত", "Absent");
  const authorityNotice = a.mediation?.authorityNotifications?.find((x) => x.kind === "FAILURE_RETURN");
  return <div className={ui.readable}>
    <Link className={ui.textBtn} href="/dashboard/dlo/mediation-outcomes">← {tx("ব্যর্থ মধ্যস্থতা কার্যতালিকা", "Failure review worklist")}</Link>
    <div className={ui.queuePlainHead}><span className={ui.heroKicker}>{tx("মধ্যস্থতা ব্যর্থতা / রেফারেল রেকর্ড", "MEDIATION FAILURE / REFERRAL RECORD")}</span><h1 className={ui.queueTitle}>{record.recordId}</h1><p className={styles.lead}>{record.caseId} · {statusLabel(record.status, lang)}</p></div>
    {message ? <div className={`${ui.banner} ${message.ok ? ui.bannerOk : ui.bannerErr}`} role={message.ok ? "status" : "alert"}>{message.text}</div> : null}
    <section className={ui.flowStep}><div className={ui.sectionHead}>{tx("আনুষ্ঠানিক রেকর্ড", "Formal record")}</div><div className={ui.rows}><Row label={tx("কেস আইডি", "Case ID")}>{record.caseId}</Row><Row label={tx("মধ্যস্থতার ধরন", "Mediation type")}>{record.mediationType === "COURT_REFERRED" ? tx("আদালত-প্রেরিত", "Court-referred") : tx("মামলা-পূর্ব", "Pre-case")}</Row><Row label={tx("মধ্যস্থতাকারী", "Mediator")}>{record.mediator.name}</Row><Row label={tx("তারিখ", "Date")}>{record.mediationDate}</Row><Row label={tx("উপস্থিতি", "Attendance")}>{tx("আবেদনকারী", "Applicant")}: {attendance("APPLICANT")} · {tx("প্রতিপক্ষ", "Respondent")}: {attendance("RESPONDENT")}</Row><Row label={tx("আলোচিত বিষয়", "Issues discussed")}>{record.issuesDiscussed}</Row><Row label={tx("ফলাফল", "Outcome")}>{record.outcome}</Row>{record.reasonStatus ? <Row label={tx("কারণ / অবস্থা", "Reason / status")}>{record.reasonStatus}</Row> : null}{record.followUpRequirement ? <Row label={tx("ফলো-আপ", "Follow-up")}>{record.followUpRequirement}</Row> : null}<Row label={tx("প্রক্রিয়াগত তথ্য", "Procedural information")}>{record.relevantProceduralInformation.sessionNumber ? `${tx("সেশন", "Session")} ${record.relevantProceduralInformation.sessionNumber}` : "—"} · {record.relevantProceduralInformation.channel ?? "—"} · {record.relevantProceduralInformation.completedAt ? formatDateTime(record.relevantProceduralInformation.completedAt, lang) : "—"}</Row><Row label={tx("গোপনীয়তা", "Confidentiality")}>{tx("গোপন একান্ত আলোচনার বিষয় এই রেকর্ডে নেই।", "Confidential caucus content is excluded from this record.")}</Row>{record.additionalInformation.map((item, index) => <Row key={`${item.at}-${index}`} label={tx("অতিরিক্ত তথ্য", "Additional information")}>{item.text} · {item.byName} · {formatDateTime(item.at, lang)}</Row>)}</div></section>
    <section className={ui.flowStep}><div className={ui.sectionHead}>{tx("সিস্টেমের পরামর্শ", "SYSTEM SUGGESTION")}</div><div className={ui.advice}><strong>{pathLabel(record.systemSuggestion.pathway, lang)}</strong><div>{suggestionReason(record.systemSuggestion.pathway, lang)}</div><div className={styles.hint}>{tx("এটি পরামর্শমাত্র এবং নিজে থেকে পথ নির্ধারণ করে না।", "This is advisory and does not set the final pathway.")}</div></div></section>
    <section className={ui.flowStep}><div className={ui.sectionHead}>{tx("লিগ্যাল এইড অফিসারের পর্যালোচনা", "LEGAL AID OFFICER REVIEW")}</div>
      {record.confirmedPathway ? <><div className={`${ui.banner} ${ui.bannerOk}`}><strong>{tx("নিশ্চিত পথ", "Confirmed pathway")}: {pathLabel(record.confirmedPathway, lang)}</strong><br />{record.officerReview.byName} · {record.officerReview.at ? formatDateTime(record.officerReview.at, lang) : ""} · {record.officerReview.note}</div>{record.confirmedPathway === "LAWYER_ASSIGNMENT" ? <><div className={ui.modeBar}>{[tx("মধ্যস্থতা", "Mediation"), tx("ব্যর্থতা", "Failure"), tx("রেফারেল রেকর্ড", "Referral record"), tx("লিগ্যাল এইড অফিসার", "Legal Aid Officer"), tx("আইনজীবী নিয়োগ", "Lawyer assignment")].map((step) => <span className={ui.tag} key={step}>✓ {step}</span>)}</div><Link className={ui.textBtn} href={`/dashboard/dlo#app/${encodeURIComponent(applicationId)}`}>{tx("প্যানেল আইনজীবী নিয়োগ খুলুন →", "Open panel-lawyer assignment →")}</Link></> : null}</> : <>
        {record.status === "MORE_INFORMATION_REQUESTED" ? <div className={`${ui.banner} ${ui.bannerWarn}`}>{tx("মধ্যস্থতাকারীর উত্তরের অপেক্ষায়", "Waiting for the mediator's response")}: {record.officerReview.note}</div> : null}
        <label className={styles.field}><span className={styles.label}>{tx("পথ নির্বাচন", "Select pathway")}</span><select className={styles.select} value={selected} onChange={(e) => setSelected(e.target.value as FailureReferralPathway)}>{PATHWAYS.map((p) => <option value={p.code} key={p.code}>{p[lang]}</option>)}</select></label>
        <label className={styles.field}><span className={styles.label}>{tx("সিদ্ধান্ত / তথ্য অনুরোধের কারণ", "Reason for decision or information request")}</span><textarea className={styles.textarea} value={note} onChange={(e) => setNote(e.target.value)} /></label>
        <div className={styles.actions}><Button disabled={record.status === "MORE_INFORMATION_REQUESTED" || note.trim().length < 5} onClick={() => run(() => MediationFailureReviewService.confirmReferral(applicationId, { pathway: record.systemSuggestion.pathway, changed: false, note }), tx("রেফারেল নিশ্চিত হয়েছে।", "Referral confirmed."))}>{tx("রেফারেল নিশ্চিত করুন", "Confirm referral")}</Button><Button variant="secondary" disabled={record.status === "MORE_INFORMATION_REQUESTED" || selected === record.systemSuggestion.pathway || note.trim().length < 5} onClick={() => run(() => MediationFailureReviewService.confirmReferral(applicationId, { pathway: selected, changed: true, note }), tx("পরিবর্তিত পথ নিশ্চিত হয়েছে।", "Changed pathway confirmed."))}>{tx("পথ পরিবর্তন করুন", "Change pathway")}</Button><Button variant="secondary" disabled={record.status === "MORE_INFORMATION_REQUESTED" || note.trim().length < 5} onClick={() => run(() => MediationFailureReviewService.requestMoreInformation(applicationId, note), tx("আরও তথ্য চাওয়া হয়েছে।", "More information requested."))}>{tx("আরও তথ্য চান", "Request more information")}</Button></div>
      </>}
    </section>
    {authorityNotice ? <section className={ui.flowStep}><div className={ui.sectionHead}>{tx("আদালত / কর্তৃপক্ষের পথে ফেরত", "Return to court / authority")}</div><div className={ui.banner}>{tx("বাহ্যিক প্রেরণ DEMO / SIMULATED। ডিসপ্যাচ রেফারেন্স নথিভুক্ত করুন।", "External dispatch is DEMO / SIMULATED. Record the dispatch reference.")}</div><div className={ui.rows}><Row label={tx("কর্তৃপক্ষ", "Authority")}>{authorityNotice.authority}</Row><Row label={tx("অবস্থা", "Status")}>{authorityNotice.status}</Row></div>{authorityNotice.status === "PENDING_DISPATCH" ? <div className={styles.actions}><input className={styles.input} value={dispatchReference} onChange={(e) => setDispatchReference(e.target.value)} placeholder={tx("ডিসপ্যাচ রেফারেন্স", "Dispatch reference")} /><Button disabled={dispatchReference.trim().length < 3} onClick={() => run(() => CourtAuthorityService.recordDispatch(applicationId, authorityNotice.notificationId, dispatchReference, "Failure record returned to referring authority"), tx("ফেরত পাঠানোর রেকর্ড সংরক্ষিত।", "Return dispatch recorded."))}>{tx("ডিসপ্যাচ নথিভুক্ত করুন", "Record dispatch")}</Button></div> : null}</section> : null}
  </div>;
}
