"""Initial Shakkho backend foundation.

Revision ID: 0001
Revises: None
Create Date: 2026-09-20 01:25:22.189976
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=80), nullable=False),
        sa.Column("case_type", sa.String(length=80), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sensitivity", sa.String(length=40), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_case_type"), "cases", ["case_type"], unique=False)
    op.create_index(op.f("ix_cases_reference"), "cases", ["reference"], unique=True)
    op.create_table(
        "organisations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("organisation_type", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "actors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("template", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_notification_outbox_case_id"), "notification_outbox", ["case_id"], unique=False
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_actor_id"), "assignments", ["actor_id"], unique=False)
    op.create_index(op.f("ix_assignments_case_id"), "assignments", ["case_id"], unique=False)
    op.create_table(
        "claim_packets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claim_packets_case_id"), "claim_packets", ["case_id"], unique=False)
    op.create_table(
        "commitments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("expected_event", sa.String(length=160), nullable=False),
        sa.Column("responsible_actor_id", sa.Uuid(), nullable=True),
        sa.Column("due_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("freshness_window_hours", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_actor_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commitments_case_id"), "commitments", ["case_id"], unique=False)
    op.create_table(
        "claim_packet_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("packet_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_code", sa.String(length=100), nullable=False),
        sa.Column("evidence_ref", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["packet_id"],
            ["claim_packets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claim_packet_items_packet_id"), "claim_packet_items", ["packet_id"], unique=False
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_actor_id", sa.Uuid(), nullable=True),
        sa.Column("source_organisation_id", sa.Uuid(), nullable=True),
        sa.Column("source_channel", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_ref", sa.String(length=500), nullable=True),
        sa.Column("supersedes_observation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["commitment_id"],
            ["commitments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_observation_id"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observations_commitment_id"), "observations", ["commitment_id"], unique=False
    )
    op.create_index(op.f("ix_observations_field"), "observations", ["field"], unique=False)
    op.create_table(
        "resolutions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("chosen_value", sa.JSON(), nullable=False),
        sa.Column("officer_id", sa.Uuid(), nullable=False),
        sa.Column("authority_basis", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["commitment_id"],
            ["commitments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resolutions_commitment_id"), "resolutions", ["commitment_id"], unique=False
    )
    op.create_index(op.f("ix_resolutions_field"), "resolutions", ["field"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key"),
    )
    op.create_table(
        "milestone_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("current_state", sa.String(length=60), nullable=False),
        sa.Column("current_value", sa.JSON(), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commitment_id"],
            ["commitments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["resolutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("commitment_id", "field"),
    )
    op.create_index(
        op.f("ix_milestone_states_commitment_id"),
        "milestone_states",
        ["commitment_id"],
        unique=False,
    )
    op.create_table(
        "resolution_observations",
        sa.Column("resolution_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.ForeignKeyConstraint(["resolution_id"], ["resolutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("resolution_id", "observation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resolution_observations")
    op.drop_index(op.f("ix_milestone_states_commitment_id"), table_name="milestone_states")
    op.drop_table("milestone_states")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_resolutions_field"), table_name="resolutions")
    op.drop_index(op.f("ix_resolutions_commitment_id"), table_name="resolutions")
    op.drop_table("resolutions")
    op.drop_index(op.f("ix_observations_field"), table_name="observations")
    op.drop_index(op.f("ix_observations_commitment_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_claim_packet_items_packet_id"), table_name="claim_packet_items")
    op.drop_table("claim_packet_items")
    op.drop_index(op.f("ix_commitments_case_id"), table_name="commitments")
    op.drop_table("commitments")
    op.drop_index(op.f("ix_claim_packets_case_id"), table_name="claim_packets")
    op.drop_table("claim_packets")
    op.drop_index(op.f("ix_assignments_case_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_actor_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_notification_outbox_case_id"), table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_table("actors")
    op.drop_table("organisations")
    op.drop_index(op.f("ix_cases_reference"), table_name="cases")
    op.drop_index(op.f("ix_cases_case_type"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
