from enum import StrEnum


class EvidenceState(StrEnum):
    PENDING = "PENDING"
    REPORTED = "REPORTED"
    CORROBORATED = "CORROBORATED"
    VERIFIED = "VERIFIED"
    DISPUTED = "DISPUTED"
    MISSING = "MISSING"
    STALE = "STALE"
    VERIFIED_WITH_RESOLVED_CONFLICT = "VERIFIED_WITH_RESOLVED_CONFLICT"
